version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    commit-message:
      prefix: "ci:"
    labels:
      - c:deps
      - c:testing

  # Manage Go pacakge versions.
  - package-ecosystem: gomod
    directory: go/
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    commit-message:
      prefix: "go:"
    labels:
      - c:deps
      - golang
    ignore:
      # Tendermint is manualy kept up to date.
      - dependency-name: github.com/tendermint/tendermint
      - dependency-name: github.com/tendermint/tm-db

  # Manage Rust pacakge versions.
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    commit-message:
      prefix: "rust:"
    labels:
      - c:deps
      - rust
    ignore:
      # We are using a ring-sgx patch, so ring is manually updated.
      # https://github.com/oasislabs/ring-sgx
      - dependency-name: ring
      # Webpki update forces ring update.
      - dependency-name: webpki
      # Wait with update until https://github.com/Amanieu/intrusive-rs/pull/51
      # is merged and released, so we can continue using `intrusive_adapter!`
      # macro in`lru_cache.rs`.
      - dependency-name: intrusive-collections
