[package]
name = "oasis-core-tools"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.7"
clap = "2.29.1"
ansi_term = "0.12.1"

[[bin]]
name = "cargo-elf2sgxs"
path ="bin/cargo-elf2sgxs.rs"
